/* Preserved CBE output of cpp100 case 23: conditional branch push/pop regression. */
/* Generated by tools/cpp-cli/adapt.py. */
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
typedef unsigned char bool;
#endif

#define __forceinline inline
#define __ATTRIBUTE_WEAK__
#define __MSVC_INLINE__
#define __ATTRIBUTELIST__(x)
#define __FUNCTIONALIGN__(x)
#define __attribute__(x)
#define __builtin_expect(value, expected) (value)
#define __builtin_unreachable() do { } while (0)


/* Global Declarations */

/* Types Declarations */

/* Function definitions */




/* Types Definitions */

/* Global Variable Declarations */
static uint32_t input;
static uint32_t result;

/* Function Declarations */
static uint32_t _ZN8case_0233runEm(uint32_t _1) __ATTRIBUTELIST__((noinline, nothrow));
static uint32_t case_023_run(uint32_t _22) __ATTRIBUTELIST__((noinline, nothrow));
void __stcxx_run_global_ctors(void) __ATTRIBUTELIST__((noinline, nothrow));
uint16_t __stcxx_bridge_ctor_count(void);
void __stcxx_bridge_invoke_ctor(uint16_t _43);
void __stcxx_abi_stc_arduino_cxx_v1_mcs251_be_size4_pdiff4_ptr3_fnptr3_guard1_direct(void) __ATTRIBUTELIST__((noinline, nothrow));
void stcxx_runtime_panic(uint8_t _35) __ATTRIBUTELIST__((noinline, nothrow));
void setup(void) __ATTRIBUTELIST__((noinline, nothrow));
void loop(void) __ATTRIBUTELIST__((noinline, nothrow));


/* Global Variable Definitions and Initialization */
static uint32_t input = 1;
static uint32_t result;


/* LLVM Intrinsic Builtin Function Bodies */
static __forceinline uint16_t llvm_add_u16(uint16_t a, uint16_t b) {
  uint16_t r = a + b;
  return r;
}
static __forceinline uint32_t llvm_add_u32(uint32_t a, uint32_t b) {
  uint32_t r = a + b;
  return r;
}
static __forceinline uint32_t llvm_mul_u32(uint32_t a, uint32_t b) {
  uint32_t r = a * b;
  return r;
}
static __forceinline uint16_t llvm_and_u16(uint16_t a, uint16_t b) {
  uint16_t r = a & b;
  return r;
}


/* Function Bodies */

static uint32_t _ZN8case_0233runEm(uint32_t _1) {
  uint32_t _2;    /* Address-exposed local */
  uint32_t _3;    /* Address-exposed local */
  uint16_t _4;    /* Address-exposed local */
  uint16_t _5;
  uint16_t _6;
  uint32_t _7;
  uint16_t _8;
  uint16_t _9;
  uint32_t _10;
  uint32_t _11;
  uint16_t _12;
  uint32_t _13;

  _2 = _1;
  _3 = 0;
  _4 = 0;
  goto _14;

  do {     /* Syntactic loop '' to make GCC happy */
_14:
  _5 = _4;
  if ((((uint16_t)_5) < ((uint16_t)((uint16_t)32)))) {
    goto _15;
  } else {
    goto _16;
  }

_15:
  _6 = _4;
  _7 = _2;
  if (((((uint32_t)(uint16_t)_6)) == (llvm_add_u32((_7 & 15), 16)))) {
    goto _17;
  } else {
    goto _18;
  }

_18:
  _8 = _4;
  if (((llvm_and_u16(_8, 1)) != ((uint16_t)0))) {
    goto _19;
  } else {
    goto _20;
  }

_20:
  _9 = _4;
  _10 = _2;
  _11 = _3;
  _3 = (llvm_add_u32(_11, (llvm_mul_u32((((uint32_t)(uint16_t)_9)), _10))));
  goto _21;

_19:
  goto _21;

_21:
  _12 = _4;
  _4 = (llvm_add_u16(_12, 1));
  goto _14;

  } while (1); /* end of syntactic loop '' */
_17:
  goto _16;

_16:
  _13 = _3;
  return _13;
}


static uint32_t case_023_run(uint32_t _22) {
  uint32_t _23;    /* Address-exposed local */
  uint32_t _24;
  uint32_t _25;

  _23 = _22;
  _24 = _23;
  _25 = _ZN8case_0233runEm(_24);
  return _25;
}


void __stcxx_run_global_ctors(void) {
  uint16_t _26;    /* Address-exposed local */
  uint16_t _27;
  uint16_t _28;
  uint16_t _29;
  uint16_t _30;

  _26 = 0;
  goto _31;

  do {     /* Syntactic loop '' to make GCC happy */
_31:
  _27 = _26;
  _28 = __stcxx_bridge_ctor_count();
  if ((((uint16_t)_27) < ((uint16_t)_28))) {
    goto _32;
  } else {
    goto _33;
  }

_32:
  _29 = _26;
  __stcxx_bridge_invoke_ctor(_29);
  goto _34;

_34:
  _30 = _26;
  _26 = (llvm_add_u16(_30, 1));
  goto _31;

  } while (1); /* end of syntactic loop '' */
_33:
  return;
}


void __stcxx_abi_stc_arduino_cxx_v1_mcs251_be_size4_pdiff4_ptr3_fnptr3_guard1_direct(void) {
  return;
}


void stcxx_runtime_panic(uint8_t _35) {
  uint8_t _36;    /* Address-exposed local */
  uint8_t _37;

  _36 = _35;
  _37 = _36;
  *(volatile uint32_t*)(&result) = (((uint32_t)(uint8_t)_37));
  goto _38;

  do {     /* Syntactic loop '' to make GCC happy */
_38:
  goto _38;

  } while (1); /* end of syntactic loop '' */
}


void setup(void) {
  uint32_t _39;
  uint32_t _40;

  __stcxx_run_global_ctors();
  _39 = *(volatile uint32_t*)(&input);
  _40 = case_023_run(_39);
  *(volatile uint32_t*)(&result) = _40;
}


void loop(void) {
  uint32_t _41;
  uint32_t _42;

  _41 = *(volatile uint32_t*)(&input);
  _42 = case_023_run(_41);
  *(volatile uint32_t*)(&result) = _42;
}

/* Constructor bridge generated from llvm.global_ctors. */
extern void main(void);

void __stcxx_bridge_require_core_main(void)
{
  (void)main();
}

void __stcxx_bridge_require_abi(void)
{
  __stcxx_abi_stc_arduino_cxx_v1_mcs251_be_size4_pdiff4_ptr3_fnptr3_guard1_direct();
}

uint16_t __stcxx_bridge_ctor_count(void)
{
  return (uint16_t)0u;
}

void __stcxx_bridge_invoke_ctor(uint16_t index)
{
  switch (index) {
  default:
    stcxx_runtime_panic(2);
    return;
  }
}

unsigned long get_result(void){return result;}void set_input(unsigned long x){input=x;}

__sfr __at(0x99) SBUF;
extern void setup(void);extern void loop(void);
extern unsigned long get_result(void);extern void set_input(unsigned long);
static void hex(unsigned long x){unsigned char i;for(i=0;i<8;i++){unsigned char b=x>>28;SBUF=b<10?'0'+b:'A'+b-10;x<<=4;}SBUF='\n';}
void main(void){setup();set_input(0x0UL);loop();hex(get_result());set_input(0x1UL);loop();hex(get_result());set_input(0x2UL);loop();hex(get_result());set_input(0x3UL);loop();hex(get_result());set_input(0x7UL);loop();hex(get_result());set_input(0xfUL);loop();hex(get_result());set_input(0x1fUL);loop();hex(get_result());set_input(0x7fUL);loop();hex(get_result());set_input(0xffUL);loop();hex(get_result());set_input(0x100UL);loop();hex(get_result());set_input(0x101UL);loop();hex(get_result());set_input(0xffffUL);loop();hex(get_result());set_input(0x10000UL);loop();hex(get_result());set_input(0x7fffffffUL);loop();hex(get_result());set_input(0x80000000UL);loop();hex(get_result());set_input(0xffffffffUL);loop();hex(get_result());set_input(0x12345678UL);loop();hex(get_result());set_input(0x89abcdefUL);loop();hex(get_result());set_input(0x1020304UL);loop();hex(get_result());set_input(0xffff0001UL);loop();hex(get_result()); SBUF='D';SBUF='O';SBUF='N';SBUF='E';SBUF='\n';for(;;){}}
